import React, { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { 
  Brain, 
  Sparkles, 
  Video, 
  BarChart3, 
  Target, 
  Zap, 
  TrendingUp, 
  CheckCircle, 
  ArrowRight,
  Mic,
  MessageSquare,
  Award,
  Users,
  Star
} from "lucide-react";
import api from "../Api";

export default function Home() {
  const navigate = useNavigate();

  const refreshToken = async () => {
    try {
      await api.post("/refresh-token");
      console.log("Token refreshed successfully");
    } catch (err) {
      console.error("Error refreshing token:", err.response?.data?.message || err.message);
    }
  };

  useEffect(() => {
    refreshToken();
    const interval = setInterval(refreshToken, 1000 * 60 * 2);
    return () => clearInterval(interval);
  }, []);

  const features = [
    {
      icon: Brain,
      title: "AI-Generated Questions",
      desc: "Get domain-specific questions dynamically generated by advanced AI models.",
      gradient: "from-indigo-500 to-purple-600"
    },
    {
      icon: Video,
      title: "Audio & Video Interviews",
      desc: "Practice using real-time video or voice interviews with instant AI feedback.",
      gradient: "from-purple-500 to-pink-600"
    },
    {
      icon: MessageSquare,
      title: "Personalized Feedback",
      desc: "Receive instant insights on your tone, fluency, confidence, and content quality.",
      gradient: "from-pink-500 to-rose-600"
    },
    {
      icon: BarChart3,
      title: "Progress Tracking",
      desc: "Monitor your performance improvements with detailed analytics and reports.",
      gradient: "from-blue-500 to-cyan-600"
    }
  ];

  const testimonials = [
    {
      text: "The AI helped me identify weak spots in my answers. I landed my dream job after just 3 mock sessions!",
      name: "Priya Sharma",
      role: "Software Engineer",
      rating: 5
    },
    {
      text: "I felt like I was in a real interview. The feedback was incredibly detailed and accurate!",
      name: "Rahul Mehta",
      role: "Product Manager",
      rating: 5
    },
    {
      text: "Practiced for Data Science interviews — AI-generated questions were spot-on and challenging!",
      name: "Megha Patel",
      role: "Data Scientist",
      rating: 5
    }
  ];

  const stats = [
    { number: "10K+", label: "Interviews Conducted" },
    { number: "95%", label: "Success Rate" },
    { number: "50+", label: "Career Domains" },
    { number: "4.9/5", label: "User Rating" }
  ];

  return (
    <div className="bg-gradient-to-br from-gray-50 via-white to-indigo-50/30 min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        {/* Background decoration */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 -left-48 w-96 h-96 bg-indigo-200 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob"></div>
          <div className="absolute top-1/3 -right-48 w-96 h-96 bg-purple-200 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-2000"></div>
        </div>

        <div className="relative max-w-7xl mx-auto px-6 md:px-12 py-20 md:py-32">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7 }}
            >
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-50 rounded-full mb-6">
                <Sparkles className="w-4 h-4 text-indigo-600" />
                <span className="text-sm font-medium text-indigo-600">AI-Powered Interview Platform</span>
              </div>
              
              <h1 className="text-5xl md:text-6xl font-extrabold text-gray-900 leading-tight mb-6">
                Ace Your Next Interview with{" "}
                <span className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">
                  AI Precision
                </span>
              </h1>
              
              <p className="text-lg text-gray-600 leading-relaxed mb-8">
                Practice real interview scenarios powered by advanced AI. Get instant feedback on communication, 
                confidence, and content quality. Transform your interview skills today.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4">
                <button
                  onClick={() => navigate("/select-role")}
                  className="group relative inline-flex items-center justify-center"
                >
                  <div className="absolute inset-0 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-xl blur opacity-60 group-hover:opacity-100 transition-opacity duration-300"></div>
                  <div className="relative flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-semibold shadow-lg hover:shadow-xl transition-all duration-200">
                    <Zap className="w-5 h-5" />
                    Start Interview
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform duration-200" />
                  </div>
                </button>
                
                <button
                  onClick={() => navigate("/about")}
                  className="inline-flex items-center justify-center gap-2 px-8 py-4 border-2 border-gray-300 text-gray-700 rounded-xl font-semibold hover:border-indigo-300 hover:bg-indigo-50/50 transition-all duration-200"
                >
                  <Target className="w-5 h-5" />
                  Learn More
                </button>
              </div>
              
              {/* Stats */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 mt-12 pt-12 border-t border-gray-200">
                {stats.map((stat, index) => (
                  <div key={index} className="text-center">
                    <div className="text-2xl md:text-3xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                      {stat.number}
                    </div>
                    <div className="text-sm text-gray-600 mt-1">{stat.label}</div>
                  </div>
                ))}
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.2, duration: 0.6 }}
              className="relative"
            >
              <div className="absolute inset-0 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-3xl blur-3xl opacity-20"></div>
              <div className="relative bg-white/50 backdrop-blur-xl rounded-3xl p-8 border border-gray-200/50 shadow-2xl">
                <div className="aspect-square bg-gradient-to-br from-indigo-100 via-purple-100 to-pink-100 rounded-2xl flex items-center justify-center">
                  <Brain className="w-32 h-32 text-indigo-600" />
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6 md:px-12">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-purple-50 rounded-full mb-4">
              <Sparkles className="w-4 h-4 text-purple-600" />
              <span className="text-sm font-medium text-purple-600">Features</span>
            </div>
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Why Choose Our Platform?
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Experience the future of interview preparation with cutting-edge AI technology
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                  viewport={{ once: true }}
                  whileHover={{ y: -8 }}
                  className="group relative"
                >
                  <div className="absolute inset-0 bg-gradient-to-r opacity-0 group-hover:opacity-10 rounded-2xl transition-opacity duration-300" 
                       style={{ background: `linear-gradient(135deg, var(--tw-gradient-stops))` }}></div>
                  <div className="relative p-6 bg-white rounded-2xl border border-gray-200/50 hover:border-indigo-200 hover:shadow-xl transition-all duration-300">
                    <div className={`inline-flex items-center justify-center w-14 h-14 rounded-xl bg-gradient-to-br ${feature.gradient} mb-4 shadow-lg`}>
                      <Icon className="w-7 h-7 text-white" />
                    </div>
                    <h4 className="text-lg font-bold text-gray-900 mb-2">
                      {feature.title}
                    </h4>
                    <p className="text-gray-600 text-sm leading-relaxed">
                      {feature.desc}
                    </p>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 px-6 md:px-12 bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-white rounded-full mb-4 shadow-sm">
              <Users className="w-4 h-4 text-indigo-600" />
              <span className="text-sm font-medium text-indigo-600">Testimonials</span>
            </div>
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Hear from Our Users
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Join thousands of successful candidates who transformed their interview skills
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((review, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                viewport={{ once: true }}
                whileHover={{ y: -5 }}
                className="relative group"
              >
                <div className="absolute inset-0 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl opacity-0 group-hover:opacity-10 transition-opacity duration-300"></div>
                <div className="relative bg-white/80 backdrop-blur-xl p-8 rounded-2xl border border-gray-200/50 shadow-lg hover:shadow-2xl transition-all duration-300">
                  <div className="flex gap-1 mb-4">
                    {[...Array(review.rating)].map((_, i) => (
                      <Star key={i} className="w-5 h-5 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                  <p className="text-gray-700 leading-relaxed mb-6 italic">
                    "{review.text}"
                  </p>
                  <div className="flex items-center gap-3 pt-6 border-t border-gray-200">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white font-bold text-lg shadow-md">
                      {review.name.charAt(0)}
                    </div>
                    <div>
                      <div className="font-bold text-gray-900">{review.name}</div>
                      <div className="text-sm text-gray-600">{review.role}</div>
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-6 md:px-12">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="relative"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-3xl blur-3xl opacity-20"></div>
            <div className="relative bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-600 rounded-3xl p-12 shadow-2xl">
              <div className="flex items-center justify-center gap-2 mb-6">
                <Award className="w-8 h-8 text-yellow-300" />
                <span className="text-yellow-300 font-semibold text-lg">Start Your Journey Today</span>
              </div>
              <h3 className="text-3xl md:text-4xl font-bold text-white mb-4">
                Ready to Transform Your Interview Skills?
              </h3>
              <p className="text-indigo-100 text-lg mb-8 max-w-2xl mx-auto">
                Join thousands of successful candidates and practice with AI-powered interviews
              </p>
              <button
                onClick={() => navigate("/start-interview")}
                className="group inline-flex items-center gap-3 px-10 py-5 bg-white text-indigo-600 rounded-xl font-bold text-lg shadow-xl hover:shadow-2xl hover:scale-105 transition-all duration-200"
              >
                <TrendingUp className="w-6 h-6" />
                Start Practicing Now
                <ArrowRight className="w-6 h-6 group-hover:translate-x-1 transition-transform duration-200" />
              </button>
            </div>
          </motion.div>
        </div>
      </section>

      <style jsx>{`
        @keyframes blob {
          0%, 100% {
            transform: translate(0, 0) scale(1);
          }
          33% {
            transform: translate(30px, -50px) scale(1.1);
          }
          66% {
            transform: translate(-20px, 20px) scale(0.9);
          }
        }
        .animate-blob {
          animation: blob 7s infinite;
        }
        .animation-delay-2000 {
          animation-delay: 2s;
        }
      `}</style>
    </div>
  );
}